
import React, { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react';

type Theme = 'light' | 'dark';
type Language = 'en' | 'vi';

export interface ThemeConfig {
  mode: 'light' | 'dark' | 'system';
  scheduleEnabled: boolean;
  dayStart: string;
  nightStart: string;
}

interface ThemeContextType {
  theme: Theme;
  setTheme: (theme: Theme) => void;
  language: Language;
  setLanguage: (lang: Language) => void;
  brightness: number;
  setBrightness: (val: number) => void;
  t: (key: string) => string;
  setThemeConfig: (config: ThemeConfig) => void;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // --- PIN & Security ---
    'Mã PIN chủ (Master PIN)': 'Master PIN (4 digits)',
    'Chỉ Chủ quán (Admin) được đổi PIN': 'Only Admin can change PIN',
    'Chỉ được nhập số (0-9)': 'Numbers only (0-9)',
    'Manager phải nhập PIN khi hủy order': 'Manager needs PIN to Cancel Order',
    'Manager phải nhập PIN khi xóa món': 'Manager needs PIN to Void Item',
    'Manager phải nhập PIN khi giảm giá': 'Manager needs PIN to Discount',
    'Manager phải nhập PIN khi in lại hóa đơn': 'Manager needs PIN to Reprint',
    'Bắt buộc Manager xác thực cho các thao tác nhạy cảm': 'Enforce Manager auth for sensitive actions',
    'Reprint Receipt': 'Reprint Receipt',
    'Admin Only': 'Admin Only',
    'Mã PIN chung (4 số)': 'Shared PIN (4 digits)',

    // --- Defaults / Common ---
    'Home': 'Home',
    'Dashboard': 'Dashboard',
    'Menu': 'Menu',
    'Tables': 'Tables',
    'Reports': 'Reports',
    'Stock': 'Stock',
    'Settings': 'Settings',
    'Logout': 'Logout',
    'More': 'More',
    'Main Branch': 'Main Branch',
    'Back': 'Back',
    'Close': 'Close',
    'Confirm': 'Confirm',
    'Cancel': 'Cancel',
    'Save': 'Save',
    'Edit': 'Edit',
    'Delete': 'Delete',
    'Add': 'Add',
    'Search': 'Search',
    'Filter': 'Filter',
    'Sort': 'Sort',
    'View': 'View',
    'Print': 'Print',
    'Export': 'Export',
    'Import': 'Import',
    'Download': 'Download',
    'Upload': 'Upload',
    'Success': 'Success',
    'Error': 'Error',
    'Warning': 'Warning',
    'Info': 'Info',
    'Loading': 'Loading',
    'Processing': 'Processing',
    'Online': 'Online',
    'Offline': 'Offline',
    'Syncing': 'Syncing',
    'Synced': 'Synced',
    'Pending': 'Pending',
    'Completed': 'Completed',
    'Cancelled': 'Cancelled',
    'Active': 'Active',
    'Inactive': 'Inactive',
    'Enabled': 'Enabled',
    'Disabled': 'Disabled',
    'Yes': 'Yes',
    'No': 'No',
    'None': 'None',
    'All': 'All',
    'Total': 'Total',
    'Subtotal': 'Subtotal',
    'Discount': 'Discount',
    'Tax': 'Tax',
    'Service Charge': 'Service Charge',
    'Tip': 'Tip',
    'Grand Total': 'Grand Total',
    'Amount': 'Amount',
    'Quantity': 'Quantity',
    'Price': 'Price',
    'Cost': 'Cost',
    'Profit': 'Profit',
    'Margin': 'Margin',
    'Revenue': 'Revenue',
    'Expense': 'Expense',
    'Net Income': 'Net Income',
    'Cash': 'Cash',
    'Card': 'Card',
    'Transfer': 'Transfer',
    'Other': 'Other',
    'Unknown': 'Unknown',
    'Note': 'Note',
    'Description': 'Description',
    'Image': 'Image',
    'Name': 'Name',
    'Code': 'Code',
    'Category': 'Category',
    'Unit': 'Unit',
    'Barcode': 'Barcode',
    'SKU': 'SKU',
    'Status': 'Status',
    'Action': 'Action',
    'Date': 'Date',
    'Time': 'Time',
    'User': 'User',
    'Role': 'Role',
    'Permission': 'Permission',
    'Staff': 'Staff',
    'Customer': 'Customer',
    'Supplier': 'Supplier',
    'Table': 'Table',
    'Order': 'Order',
    'Item': 'Item',
    'Product': 'Product',
    'Ingredient': 'Ingredient',
    'Recipe': 'Recipe',
    'Inventory': 'Inventory',
    'Report': 'Report',
    'System': 'System',
    'Configuration': 'Configuration',
    'Language': 'Language',
    'Theme': 'Theme',
    'Dark Mode': 'Dark Mode',
    'Light Mode': 'Light Mode',

    // Reports Page
    'today': 'Today',
    'yesterday': 'Yesterday',
    'week': 'Last 7 Days',
    'custom': 'custom',
    'From Date': 'From Date',
    'To Date': 'To Date',
    'Total Orders': 'Total Orders',
    // Duplicate key removed: 'Search ID or Table...'
    'All Status': 'All Status',
    'All Payment': 'All Payment',
    'No history found': 'No history found',
    'Select Order to Audit': 'Select Order to Audit',
    'Items Detail': 'Items Detail',
    'Order Note': 'Order Note',
    'Final Amount': 'Final Amount',
    'Created At': 'Created At',
    'Hourly': 'Hourly revenue performanced',
    'Daily': 'Daily',
    'Orders': 'Orders',
    'Payments': 'Payments',
    'Method': 'Method',
    '% Revenue': '% Revenue',
    'Unpaid': 'Unpaid',
    'overview': 'Overview',
    'Trends': 'Trends',
    'history': 'History',
    'Recent Activity': 'Recent Activity',
    'Export Data': 'Export Transaction Data',
    'History to Export': 'History to Export',
    'History Records': 'History Records',
    'Date Span': 'Date Span',
    'Download CSV Data': 'Download CSV Data',
    'AOV': 'AOV',
    'Cancel Rate': 'Cancel Rate',
    'Bill Total': 'Bill Total',
    'Top Selling Items': 'Top Selling Items',
    'Financial Summary': 'Financial Summary',
    'Net Sales': 'Net Sales',
    'Gross Sales': 'Gross Sales',
    'Total Discount': 'Total Discount',
    'Payment Methods': 'Payment Methods',
    'View Detailed History': 'View Detailed History',
    'Access Denied': 'Access Denied',
    'Report Access Message': 'You do not have permission to view revenue reports. Please contact manager or owner.',
    'Export Permission Denied': 'You do not have permission to export data.',

    // Dashboard & Operations
    'Dashboard Overview': 'Dashboard Overview',
    'Revenue Today': 'Revenue Today',
    'Doanh thu (Của bạn)': 'Revenue (Yours)',
    'Doanh thu hôm nay': 'Revenue Today',
    'Đang phục vụ': 'Serving',
    'Đã xong (Của bạn)': 'Completed (Yours)',
    'Đã hoàn thành': 'Completed',
    'TB Đơn': 'Avg Bill',
    'Cooking': 'Cooking',
    'Ready': 'Ready',
    'Pay': 'Pay',
    'Takeaway': 'Takeaway',
    'No orders found': 'No orders found',
    'Select an Order': 'Select an Order',
    'Personal View': 'Personal View',
    'Global View': 'Global View',
    'Search ID or Table...': 'Search ID or Table...',

    // Menu
    'Manage items': 'Manage items and manual stock',
    'Add Item': 'Add Item',
    'Search...': 'Search...',
    'Coffee': 'Coffee',
    'Non Coffee': 'Non Coffee',
    'Matcha': 'Matcha',
    'Food': 'Food',
    'Current Order': 'Current Order',
    'Total Amount': 'Total Amount',
    'Confirm Order': 'Confirm Order',
    'Cart is empty': 'Cart is empty',
    'Your Cart': 'Your Cart',
    'View Cart': 'View Cart',
    'New Menu Item': 'New Menu Item',
    'Edit Item': 'Edit Item',
    'Select Order Type': 'Select Order Type',
    'Dine-in': 'Dine-in',
    'Select table': 'Select table',
    'Draft': 'Draft',
    'Selected': 'Selected',

    // FloorPlan
    'Main Hall': 'Main Hall',
    'Live': 'Live',
    'Editor Mode': 'Editor Mode',
    'Edit Layout': 'Edit Layout',
    'Save Changes': 'Save Changes',
    'Done': 'Done',
    'Guests': 'Guests',
    'Occupied': 'Occupied',
    'Available': 'Available',
    'Empty Table': 'Empty Table',
    'Ready for service': 'Ready for service',
    'Check In & Order': 'Check In & Order',
    'Edit Order': 'Edit Order',
    'Bill': 'Bill',
    'Add Items': 'Add Items',
    'Split / Merge Table': 'Split / Merge Table',
    'Shape': 'Shape',
    'Seats': 'Seats',
    'Table Actions': 'Table Actions',
    'Move Table': 'Move Table',
    'Merge Table': 'Merge Table',
    'From Table': 'From Table',
    'Select an empty table to move to': 'Select an empty table to move to',
    'Select an occupied table to merge with': 'Select an occupied table to merge with',
    'No empty tables available': 'No empty tables available',
    'No other occupied tables': 'No other occupied tables',
    'Add Table': 'Add Table',

    // Inventory
    'Inventory Management': 'Inventory Management',
    'Manage stock': 'Manage stock, alerts and yield estimation',
    'Stock View': 'Stock View',
    'Yield Analysis': 'Yield Analysis',
    'Sync': 'Sync',
    'Total Value': 'Total Value',
    'Low Stock': 'Low Stock',
    'Action Needed': 'Action Needed',
    'All Good': 'All Good',
    'Top Item': 'Top Item',
    'Stock In': 'Stock In',
    'Add new ingredients': 'Add new ingredients',
    'Ingredient Name': 'Ingredient Name',
    'Add Stock': 'Add Stock',
    'Stock Added': 'Stock Added',
    'Inventory List': 'Inventory List',
    'Track all ingredients': 'Track all ingredients',
    'Potential Yield Analysis': 'Potential Yield Analysis',
    'Theoretical max': 'Theoretical max output based on ingredients',
    'Item Name': 'Item Name',
    'Stock Level': 'Stock Level',
    'Est. Yield': 'Est. Yield',
    'units': 'units',
    'Manual Stock': 'Manual Stock',
    'No recipe defined': 'No recipe defined',
    // Inventory Categories & Statuses
    'Pantry': 'Pantry',
    'Dairy': 'Dairy',
    'Produce': 'Produce',
    'Packaging': 'Packaging',
    'Meat': 'Meat',
    'Seafood': 'Seafood',
    'Beverages': 'Beverages',
    'Critical': 'Critical',
    'Low': 'Low',
    'Good': 'Good',
    'packs': 'packs',
    'pcs': 'pcs',

    // Payment Modal & Split Bill
    'Confirm Payment': 'Confirm Payment',
    'Total to Pay': 'Total to Pay',
    'Order #': 'Order #',
    'Auto Print Receipt': 'Auto Print Receipt',
    'Complete Order': 'Complete Order',
    'Scan to pay': 'Scan to pay',
    'VietQR Payment': 'VietQR Payment',
    'Account Owner': 'Account Owner',
    'Account Number': 'Account Number',
    'Bank': 'Bank',
    'Memo': 'Memo',
    'Bank settings required': 'Bank settings required in Settings',
    'Cannot apply discount to partially paid order': 'Cannot apply discount to partially paid order',
    'Giảm giá đang tắt trong Cài đặt.': 'Discount is disabled in Settings.',
    'Không có quyền thực hiện giảm giá.': 'Permission denied: Cannot apply discount.',
    'Sai PIN.': 'Wrong PIN.',
    'Giới hạn giảm giá tối đa là': 'Max discount limit is',
    'Giảm giá không thể quá 100%': 'Discount cannot exceed 100%',
    'Giảm giá không thể lớn hơn tổng tiền': 'Discount cannot exceed total amount',
    'Apply Discount': 'Apply Discount',
    'Discount Percentage': 'Discount Percentage',
    'Discount Amount': 'Discount Amount',
    'New Total:': 'New Total:',
    'Confirm Discount': 'Confirm Discount',
    'Cannot split a partially paid order': 'Cannot split a partially paid order',
    'Tính năng tách bill đang tắt.': 'Split Bill feature is disabled.',
    'Không có quyền thực hiện tách bill.': 'Permission denied: Cannot split bill.',
    'Split Bill Items': 'Split Bill Items',
    'Select items to move to a new bill.': 'Select items to move to a new bill.',
    'New Bill Subtotal': 'New Bill Subtotal',
    'Next: Select Table': 'Next: Select Table',
    'Select New Table': 'Select New Table',
    'Bill Split Successful!': 'Bill Split Successful!',
    'Items moved to new order.': 'Items moved to new order.',
    'Choose where to move the split items:': 'Choose where to move the split items:',
    'Failed to split order: ': 'Failed to split order: ',
    'Paid:': 'Paid:',
    'Remaining to Pay': 'Remaining to Pay',
    'Edit Discount': 'Edit Discount',
    'Split Bill': 'Split Bill',
    'Max allowed:': 'Max allowed:',
    'Empty': 'Empty',
    'Cannot split order with single item': 'Cannot split order with single item',
    'Order total must be greater than 0': 'Order total must be greater than 0',
    'Cannot remove last item. Cancel order instead.': 'Cannot remove last item. Cancel order instead.',
    
    // Reset Table Flow
    'Confirm Reset Order': 'Confirm Reset Order?',
    'Last item removal warning': 'Removing the last item will cancel the order and reset the table. Continue?',
    'Table Reset Success': 'Last item removed. Table has been reset.',

    // --- SETTINGS TRANSLATIONS ---
    
    // Status & Actions
    'Vận hành: Mượt': 'Operations: Smooth',
    'Cần chú ý': 'Needs Attention',
    'Lỗi': 'Error',
    'Nhập': 'Type',
    'để xác nhận:': 'to confirm:',
    'Huỷ': 'Cancel',
    'Hoá đơn in mẫu': 'Sample Receipt',
    'Chế độ xem trước (Sandbox)': 'Preview Mode (Sandbox)',
    'Đóng': 'Close',
    'Đã sao chép HTML': 'HTML Copied',
    'Copy nội dung': 'Copy Content',
    'Bật tính năng': 'Enable Feature',
    'Đồng ý bật': 'Agree to Enable',
    'Không tìm thấy cài đặt nào phù hợp': 'No matching settings found',
    'Saving...': 'Saving...',
    'Saved': 'Saved',
    'Tìm cài đặt...': 'Search settings...',
    'Đổi mật khẩu': 'Change Password',
    'Mật khẩu mới': 'New Password',
    'Xác nhận mật khẩu mới': 'Confirm New Password',
    'Cập nhật': 'Update',
    'Mật khẩu không khớp': 'Passwords do not match',
    'Đổi mật khẩu thành công': 'Password changed successfully',
    'Xoá dữ liệu trên máy này?': 'Delete data on this device?',
    'Thao tác này không thể hoàn tác. Nhập DELETE để xác nhận.': 'This action cannot be undone. Type DELETE to confirm.',
    'Xoá': 'Delete',
    'Đăng xuất?': 'Logout?',
    'Bạn sẽ đăng xuất khỏi phiên làm việc hiện tại.': 'You will be logged out of the current session.',
    'Đăng xuất': 'Logout',
    'Administrator access required': 'Administrator access required',
    'Administrator access required to manage users': 'Administrator access required to manage users',
    'Quản lý User & Mã PIN': 'User & PIN Management',
    'Set PIN for': 'Set PIN for',
    'Save PIN': 'Save PIN',
    'PIN updated successfully': 'PIN updated successfully',
    
    // Config Sections & Keys
    'Cài đặt hệ thống': 'System Settings',
    'Quản lý toàn bộ cấu hình quán': 'Manage entire store configuration',
    'Quán & Bán hàng': 'Store & Sales',
    'Thiết lập luồng order, thanh toán và quản lý bàn': 'Setup ordering flow, payments and table management',
    'Mô hình vận hành (Preset)': 'Operating Model (Preset)',
    'Áp dụng nhanh mô hình': 'Apply Preset Model',
    'Thông tin quầy': 'Counter Info',
    'Tên quầy / cửa hàng': 'Counter / Store Name',
    'Địa chỉ': 'Address',
    'Số điện thoại': 'Phone Number',
    'Ghi chú in hóa đơn': 'Receipt Footer Note',
    'Hiển thị ở cuối hóa đơn': 'Displays at bottom of receipt',
    'Cấu hình Ngân hàng (VietQR)': 'Bank Configuration (VietQR)',
    'Thiết lập VietQR': 'Setup VietQR',
    'Luồng bán hàng': 'Sales Flow',
    'Tạo đơn nhanh': 'Quick Order',
    'Bỏ qua bước chọn bàn, vào thẳng menu (giảm bước)': 'Skip table selection, go straight to menu',
    'Kiểu order mặc định': 'Default Order Type',
    'Chọn hình thức phục vụ chính của quán': 'Select main service type',
    'Tại bàn': 'Dine-in',
    'Mang đi': 'Takeaway',
    'Giao hàng': 'Delivery',
    'Hỏi xác nhận khi huỷ món': 'Confirm before voiding item',
    'Tránh nhân viên bấm nhầm xoá món đã gọi': 'Prevent accidental item deletion',
    'Thanh toán': 'Payment',
    'Cho phép tách bill': 'Allow Bill Splitting',
    'Tách đơn lớn thành nhiều đơn nhỏ để thanh toán': 'Split large orders into smaller ones for payment',
    'Cho phép gộp bill': 'Allow Bill Merging',
    'Gộp nhiều bàn/đơn vào một hóa đơn thanh toán': 'Merge multiple tables/orders into one bill',
    'Bật tính năng giảm giá': 'Enable Discount',
    'Cho phép nhập giảm giá theo % hoặc số tiền': 'Allow entering discount by % or amount',
    'Giới hạn giảm giá tối đa': 'Max Discount Limit',
    'Mức % giảm giá cao nhất nhân viên được phép nhập': 'Maximum % discount staff can enter',
    'Bàn & Khu vực': 'Tables & Areas',
    'Bật quản lý bàn': 'Enable Table Management',
    'Hiển thị sơ đồ bàn (Tắt nếu chỉ bán mang đi)': 'Show table map (Disable for takeaway only)',
    'Bật quản lý khu vực': 'Enable Area Management',
    'Phân chia bàn theo tầng hoặc phòng': 'Divide tables by floor or room',
    'Cảnh báo bàn mở quá lâu': 'Long Sitting Alert',
    'Hiện cảnh báo khi khách ngồi quá thời gian quy định': 'Show alert when guests exceed time limit',
    'Thời gian giới hạn': 'Time Limit',
    'Số phút tối đa trước khi cảnh báo': 'Max minutes before alert',
    'In & Hóa đơn': 'Printing & Invoice',
    'Máy in, nội dung hóa đơn và thao tác in nhanh': 'Printers, receipt content and quick print actions',
    'Máy in': 'Printer',
    'Tên máy in': 'Printer Name',
    'Kiểm tra kết nối': 'Check Connection',
    'Gửi tín hiệu đến máy in': 'Send signal to printer',
    'Khổ giấy': 'Paper Size',
    'Hành vi in': 'Printing Behavior',
    'Tự động in sau thanh toán': 'Auto-print after payment',
    'Bấm Thanh toán là in ngay': 'Print immediately upon payment',
    'In phiếu tạm khi tạo đơn': 'Print provisional bill on order',
    'Dùng khi muốn giữ bill tạm': 'For keeping temporary bills',
    'In lại khi chỉnh sửa đơn': 'Reprint on order edit',
    'Thêm món/sửa món sẽ in lại': 'Reprint when adding/editing items',
    'Nội dung hóa đơn': 'Receipt Content',
    'Hiện QR thanh toán': 'Show Payment QR',
    'Khách quét mã chuyển khoản nhanh': 'Scan code for quick transfer',
    'Hiện thông tin quán': 'Show Store Info',
    'Tên/địa chỉ/SĐT trên hóa đơn': 'Name/Address/Phone on receipt',
    'Tên Wifi': 'Wifi Name',
    'Mật khẩu Wifi': 'Wifi Password',
    'In ở cuối hóa đơn cho khách tại bàn': 'Print at bottom for dine-in guests',
    'Cỡ chữ hóa đơn': 'Receipt Font Size',
    'Khuyên dùng ‘Vừa’ cho 80mm': 'Recommended "Medium" for 80mm',
    'Nhỏ': 'Small',
    'Vừa': 'Medium',
    'Lớn': 'Large',
    'In ghi chú món': 'Print Item Notes',
    'Ghi chú nằm dưới tên món': 'Notes appear below item name',
    'Test in': 'Test Print',
    'In hóa đơn test': 'Print Test Receipt',
    'Kiểm tra máy in trước khi bán': 'Check printer before selling',
    'Nhân viên & Quyền hạn': 'Staff & Permissions',
    'Phân quyền, giới hạn thao tác nhạy cảm và bảo mật': 'Roles, sensitive actions and security',
    'Vai trò nhanh (Preset Roles)': 'Quick Roles (Presets)',
    'Tuỳ chỉnh quyền chi tiết': 'Customize Detailed Permissions',
    'Quyền quan trọng (Staff Permissions)': 'Critical Permissions',
    'Cho phép huỷ món': 'Allow Void Item',
    'Rủi ro: Nhân viên có thể huỷ đơn gian lận sau khi thu tiền.': 'Risk: Staff may fraudulently void orders after collecting cash.',
    'Cho phép nhân viên tự ý huỷ món có thể dẫn đến thất thoát doanh thu. Bạn có chắc chắn muốn bật?': 'Allowing staff to void items may lead to revenue loss. Are you sure?',
    'Cho phép xóa hoàn toàn đơn hàng': 'Allow Delete Order',
    'Rủi ro: Mất dữ liệu đơn hàng.': 'Risk: Loss of order data.',
    'Cho phép nhân viên xóa hoàn toàn đơn hàng (Cancel Order). Bạn có chắc chắn?': 'Allows staff to completely delete orders. Are you sure?',
    'Cho phép giảm giá': 'Allow Discount',
    'Rủi ro: Áp dụng giảm giá sai quy định.': 'Risk: Applying unauthorized discounts.',
    'Việc cho phép nhân viên tự giảm giá có thể bị lạm dụng. Bạn có chắc chắn?': 'Allowing staff to apply discounts may be abused. Are you sure?',
    'Cho phép xem báo cáo': 'Allow View Reports',
    'Nhân viên sẽ thấy được doanh thu tổng của quán.': 'Staff will see total store revenue.',
    'Cho phép hoàn tiền / Mở két': 'Allow Refund / Open Drawer',
    'Rủi ro cao: Thất thoát tiền mặt trực tiếp.': 'High Risk: Direct cash loss.',
    'CẢNH BÁO: Quyền này cho phép nhân viên mở két tiền và hoàn trả tiền mặt. Bạn có chắc chắn?': 'WARNING: This allows staff to open cash drawer and refund cash. Are you sure?',
    'Mã PIN thao tác nhạy cảm': 'Sensitive Action PIN',
    'Yêu cầu PIN khi huỷ món': 'Require PIN to Void Item',
    'Bắt buộc nhập mã PIN chủ quán hoặc quản lý': 'Must enter Owner or Manager PIN',
    'Yêu cầu PIN khi giảm giá': 'Require PIN to Discount',
    'Ngăn chặn giảm giá tuỳ tiện': 'Prevent unauthorized discounts',
    'Dùng để duyệt các thao tác nhạy cảm': 'Used to approve sensitive actions',
    'Cấu hình Manager (Manager Config)': 'Manager Configuration',
    'Giao diện & Trải nghiệm': 'Interface & Experience',
    'Tùy chỉnh tốc độ thao tác, hiển thị và phím tắt': 'Customize speed, display and shortcuts',
    'Giao diện & Ngôn ngữ': 'UI & Language',
    'Ngôn ngữ': 'Language',
    'Áp dụng cho toàn bộ hệ thống, không cần khởi động lại': 'Applies to entire system, no restart needed',
    'Chế độ hiển thị': 'Theme Mode',
    'Giao diện Sáng / Tối': 'Light / Dark Mode',
    'Hệ thống (System)': 'System',
    'Tối (Dark)': 'Dark',
    'Sáng (Light)': 'Light',
    'Tự động theo khung giờ (06:00–18:00 sáng, 18:00–06:00 tối)': 'Auto Schedule (06:00–18:00 Day, 18:00–06:00 Night)',
    'Tự động chuyển đổi Light/Dark': 'Auto switch Light/Dark',
    'Chỉ áp dụng khi chọn System': 'Only applies when System is selected',
    'Giờ bắt đầu Sáng': 'Day Start Time',
    'Giờ bắt đầu Tối': 'Night Start Time',
    'Tốc độ thao tác': 'Operation Speed',
    'Chạm 1 lần để thêm món': 'Single Tap to Add Item',
    'Mặc định trên tablet giúp order nhanh hơn': 'Default on tablet for faster ordering',
    'Hiện bàn phím số': 'Show Numpad',
    'Hiện popup nhập số lượng khi chọn món': 'Show quantity popup when selecting item',
    'Âm thanh beep khi thêm món': 'Beep Sound on Add',
    'Phản hồi âm thanh giúp biết đã nhận lệnh': 'Audio feedback to confirm action',
    'Hiển thị': 'Display',
    'Mật độ giao diện': 'UI Density',
    'Chọn độ thoáng của các nút bấm': 'Select spacing of buttons',
    'Thoáng': 'Spacious',
    'Dày (Compact)': 'Compact',
    'Cỡ chữ tổng': 'Global Font Size',
    'Ảnh hưởng toàn bộ ứng dụng': 'Affects entire application',
    'Chế độ tương phản cao': 'High Contrast Mode',
    'Dễ nhìn hơn trong môi trường ánh sáng mạnh': 'Easier to see in bright environments',
    'Shortcut': 'Shortcuts',
    'Bật phím tắt bàn phím': 'Enable Keyboard Shortcuts',
    'F2: Thanh toán, F3: Tìm món...': 'F2: Pay, F3: Search item...',
    'Xem danh sách phím tắt': 'View Shortcuts List',
    'Hiển thị bảng tra cứu phím tắt': 'Show shortcut reference table',
    'Báo cáo & Kiểm soát': 'Reports & Controls',
    'Giữ số liệu sạch, hạn chế thất thoát, kiểm soát vận hành': 'Clean data, prevent loss, control operations',
    'Nhật ký thao tác (Audit)': 'Action Log (Audit)',
    'Ghi log thao tác nhạy cảm': 'Log Sensitive Actions',
    'Lưu lại khi nhân viên huỷ món, giảm giá hoặc hoàn tiền': 'Log when staff void, discount or refund',
    'Ghi log đổi ca': 'Log Shift Changes',
    'Lưu thời điểm và người thực hiện giao ca': 'Log time and person changing shift',
    'Thời gian lưu log': 'Log Retention Period',
    'Tự động xoá log cũ để giảm dung lượng': 'Auto delete old logs to save space',
    '7 ngày': '7 days',
    '30 ngày': '30 days',
    '90 ngày': '90 days',
    'Cảnh báo thất thoát': 'Loss Alerts',
    'Cảnh báo khi giảm giá cao': 'High Discount Alert',
    'Hiện cảnh báo đỏ nếu % giảm giá vượt mức quy định': 'Show red alert if discount % exceeds limit',
    'Ngưỡng cảnh báo giảm giá': 'Discount Warning Threshold',
    'Ví dụ: 20% - Cao hơn mức này sẽ báo động': 'E.g., 20% - Higher will trigger alert',
    'Cảnh báo huỷ món bất thường': 'Abnormal Void Alert',
    'Phát hiện nếu một bàn bị huỷ món liên tục': 'Detect if a table has continuous voids',
    'Đóng ca (Shift Close)': 'Shift Closing',
    'Bắt buộc đóng ca cuối ngày': 'Require End of Day Close',
    'Không thể bán hàng ngày mới nếu chưa chốt ca cũ': 'Cannot start new day sales without closing old shift',
    'Yêu cầu nhập tiền thực thu': 'Require Actual Cash Count',
    'Nhân viên phải đếm tiền và nhập số liệu khi đóng ca': 'Staff must count cash and enter figures when closing',
    'Xuất báo cáo đóng ca mẫu': 'Export Sample Z-Report',
    'Xem trước mẫu báo cáo Z-Report': 'Preview Z-Report template',
    'Quyền xem báo cáo & Dữ liệu': 'Report Viewing & Data Rights',
    'Ai được xem báo cáo': 'Who can view reports',
    'Giới hạn đúng người, đúng việc': 'Limit to right people',
    'Chỉ chủ quán': 'Owner Only',
    'Chủ + quản lý': 'Owner + Manager',
    'Tất cả nhân viên': 'All Staff',
    'Ẩn doanh thu chi tiết': 'Hide Detailed Revenue',
    'Nhân viên chỉ thấy số lượng, không thấy tiền': 'Staff only see quantities, not amounts',
    'Cho phép xuất dữ liệu': 'Allow Data Export',
    'Chỉ nên bật cho chủ quán': 'Should only enable for Owner',
    'Hệ thống & An toàn': 'System & Safety',
    'Bán ổn định khi mất mạng, bảo vệ dữ liệu, yên tâm vận hành': 'Sell stably offline, protect data, operate safely',
    'Offline & Đồng bộ': 'Offline & Sync',
    'Tự động đồng bộ': 'Auto Sync',
    'Tự đẩy dữ liệu lên server khi có mạng': 'Auto push data to server when online',
    'Đồng bộ ngay': 'Sync Now',
    'Đẩy thủ công các đơn Offline lên hệ thống': 'Manually push Offline orders to system',
    'Trạng thái mạng': 'Network Status',
    'Đơn chờ đồng bộ': 'Pending Sync Orders',
    'Lần đồng bộ cuối': 'Last Sync Time',
    'Lỗi đồng bộ': 'Sync Error',
    'Sao lưu': 'Backup',
    'Xuất dữ liệu': 'Export Data',
    'Tải về file dự phòng (JSON)': 'Download backup file (JSON)',
    'Nhập dữ liệu': 'Import Data',
    'Khôi phục từ file backup': 'Restore from backup file',
    'Danger Zone': 'Danger Zone',
    'Xoá dữ liệu cục bộ': 'Clear Local Data',
    'Thao tác này sẽ xoá toàn bộ dữ liệu trên thiết bị này.': 'This will delete all data on this device.',
    'Chạy kiểm tra vận hành': 'Run System Diagnostics',
    'Quét lỗi cấu hình và rủi ro bảo mật': 'Scan for config errors and security risks',
    'Kết quả kiểm tra': 'Diagnostic Results',
    'Đạt': 'Passed',
    'Cảnh báo': 'Warning',
    'Thất bại': 'Failed',
    'Bank (VietQR)': 'Bank (VietQR)',
    'Ngân hàng': 'Bank',
    'Số tài khoản': 'Account Number',
    'Tên chủ tài khoản': 'Account Name',
    'Chọn ngân hàng': 'Select Bank',
    'Lưu cấu hình ngân hàng': 'Save Bank Config',
    'LoginDescription': 'A comprehensive dark-themed Point of Sale system for restaurants, coffee shops, bars including dashboard, menu management, floor plan, order tracking, and inventory. This free POS is built by Duc Ngo',

    // Panels & Drawers
    'Phím tắt hệ thống': 'System Shortcuts',
    'Thanh toán nhanh': 'Quick Pay',
    'Tìm kiếm món': 'Search Item',
    'In lại hóa đơn gần nhất': 'Reprint Last Receipt',
    'Đóng modal / Huỷ bỏ': 'Close Modal / Cancel',
    'Lưu cài đặt': 'Save Settings',
    'Preset Nhanh': 'Quick Preset',
    'Đã tuỳ chỉnh': 'Customized',
    'Hoàn tác': 'Undo',
    'Ghi đè chỉnh tay?': 'Overwrite manual changes?',
    'Áp dụng': 'Apply',
    'Đang áp dụng': 'Applying',
    'Áp dụng Preset': 'Apply Preset',
    'Phân quyền nhân viên': 'Staff Permissions',
    'Danh sách vai trò': 'Roles List',
    'Không có quyền': 'No Permissions',
    'Toàn quyền': 'Full Access',
    'quyền hạn': 'permissions',
    'Chi tiết': 'Details',
    'Tắt': 'Off',
    'Thêm vai trò mới (Coming Soon)': 'Add New Role (Coming Soon)',
    'Dành cho Chủ quán (Owner Mode)': 'For Owner (Owner Mode)',
    'Hệ thống Online': 'System Online',
    'Đang Offline': 'Currently Offline',
    'Kết nối ổn định': 'Stable Connection',
    'Dữ liệu sẽ được lưu cục bộ': 'Data will be saved locally',

    // Staff Roles & Permissions
    'Roles, Sensitive Actions and Security': 'Roles, Sensitive Actions and Security',
    'Phân quyền, thao tác nhạy cảm và bảo mật': 'Staff roles, sensitive actions and security',
    'Quick Roles (Presets)': 'Quick Roles (Presets)',
    'Chủ quán': 'Owner',
    'Toàn quyền truy cập và chỉnh sửa hệ thống.': 'Full access to all system features and settings.',
    'Thu ngân': 'Cashier',
    'Chuyên trách thanh toán, in hóa đơn, mở két.': 'Responsible for payment, printing receipts, and opening cash drawer.',
    'Phục vụ': 'Server',
    'Chỉ được tạo đơn, thêm món, gửi bếp.': 'Can create orders, add items, and send to kitchen.',
    'FULL ACCESS': 'FULL ACCESS',
    'PAYMENT': 'PAYMENT',
    'In ấn': 'PRINT',
    'Mở két': 'OPEN CASH DRAWER',
    'ORDER': 'ORDER',
    'Gửi bếp': 'SEND TO KITCHEN',
    'Customize Detailed Permissions': 'Customize Detailed Permissions',

    // New POS Actions
    'Lock POS': 'Lock POS',
    'Switch User': 'Switch User',
    
    // Lock Screen
    'POS Locked': 'POS Locked',
    'Enter PIN to continue': 'Enter PIN to continue',
    'Unlock': 'Unlock',
    'Invalid PIN': 'Invalid PIN',
    
    // Renamed App Keys
    'Nepos System': 'Hệ Thống Quản Lý NEPOS',
    'Welcome to Nepos': 'Chào mừng đến với Nepos',
    'Register text': 'Đăng ký để bắt đầu quản lý nhà hàng.',
    'Login text': 'Vui lòng nhập thông tin để đăng nhập.',
    'Full Name': 'Full Name',
    'Email Address': 'Email Address',
    'Password': 'Password',
    'Confirm Password': 'Confirm Password',
    'Remember me': 'Remember me',
    'Forgot password?': 'Forgot password?',
    'Create Account': 'Create Account',
    'Already have an account?': 'Already have an account?',
    'Don\'t have an account?': 'Don\'t have an account?',
    'Sign In': 'Sign In',
    'Create an Account': 'Create an Account',
  },

  vi: {
    // --- PIN & Security ---
    'Mã PIN chủ (Master PIN)': 'Mã PIN chung (4 số)',
    'Chỉ Chủ quán (Admin) được đổi PIN': 'Chỉ Chủ quán (Admin) được đổi PIN',
    'Chỉ được nhập số (0-9)': 'Chỉ được nhập số (0-9)',
    'Manager phải nhập PIN khi hủy order': 'Manager phải nhập PIN khi hủy đơn',
    'Manager phải nhập PIN khi xóa món': 'Manager phải nhập PIN khi xóa món',
    'Manager phải nhập PIN khi giảm giá': 'Manager phải nhập PIN khi giảm giá',
    'Manager phải nhập PIN khi in lại hóa đơn': 'Manager phải nhập PIN khi in lại hóa đơn',
    'Bắt buộc Manager xác thực cho các thao tác nhạy cảm': 'Bắt buộc Manager xác thực cho thao tác nhạy cảm',
    'Reprint Receipt': 'In lại hóa đơn',
    'Admin Only': 'Chỉ Admin',
    'Mã PIN chung (4 số)': 'Mã PIN chung (4 số)',

    // Sidebar
    'Home': 'Trang chủ',
    'Dashboard': 'Tổng quan',
    'Menu': 'Thực đơn',
    'Tables': 'Sơ đồ bàn',
    'Reports': 'Báo cáo',
    'Stock': 'Kho hàng',
    'Settings': 'Cài đặt',
    'Logout': 'Đăng xuất',
    'More': 'Thêm',
    'Main Branch': 'Chi nhánh chính',

    // Reports Page
    'today': 'Hôm nay',
    'yesterday': 'Hôm qua',
    'week': '7 ngày qua',
    'custom': 'Tùy chỉnh',
    'From Date': 'Từ ngày',
    'To Date': 'Đến ngày',
    // 'Revenue': 'Doanh thu', // Removed Duplicate
    'Total Orders': 'Tổng đơn hàng',
    'Search ID or Table...': 'Tìm ID hoặc Bàn...',
    'All Status': 'Tất cả trạng thái',
    'All Payment': 'Tất cả thanh toán',
    'No history found': 'Không có lịch sử',
    'Select Order to Audit': 'Chọn đơn để đối soát',
    'Items Detail': 'Chi tiết món',
    'Order Note': 'Ghi chú đơn',
    'Final Amount': 'Tổng thanh toán',
    'Staff': 'Nhân viên',
    'Created At': 'Ngày tạo',
    'Hourly': 'Doanh thu theo giờ',
    'Daily': 'Doanh thu theo ngày',
    'Orders': 'Số đơn',
    // 'Amount': 'Doanh thu', // Removed Duplicate
    'Payments': 'Thanh toán',
    '% Revenue': 'Tỷ trọng %',
    'Method': 'Phương thức',
    // 'Status': 'Trạng thái', // Removed Duplicate
    'Unpaid': 'Chưa thanh toán',
    'overview': 'Tổng quan',
    'Trends': 'Xu hướng',
    'history': 'Lịch sử GD',
    'Recent Activity': 'Giao dịch gần đây',
    'Export': 'Xuất dữ liệu',
    'Export Data': 'Xuất dữ liệu giao dịch',
    'History to Export': 'Dữ liệu xuất',
    'History Records': 'Số giao dịch',
    'Date Span': 'Khoảng thời gian',
    'Download CSV Data': 'Tải file CSV',
    'AOV': 'Giá trị đơn TB',
    'Cancel Rate': 'Tỷ lệ hủy',
    'Bill Total': 'Tổng bill',
    'Top Selling Items': 'Top món bán chạy',
    'Financial Summary': 'Tổng kết tài chính',
    'Net Sales': 'Doanh thu thuần',
    'Gross Sales': 'Doanh thu gộp',
    'Total Discount': 'Tổng giảm giá',
    'Payment Methods': 'Phương thức thanh toán',
    'View Detailed History': 'Xem lịch sử chi tiết',
    'Access Denied': 'Truy cập bị từ chối',
    'Report Access Message': 'Bạn không có quyền xem báo cáo doanh thu.\nVui lòng liên hệ quản lý hoặc chủ quán.',
    'Export Permission Denied': 'Không có quyền xuất dữ liệu.',

    // Dashboard & Operations
    'Dashboard Overview': 'Tổng quan kinh doanh',
    'Revenue Today': 'Doanh thu hôm nay',
    'Doanh thu (Của bạn)': 'Doanh thu (Của bạn)',
    'Doanh thu hôm nay': 'Doanh thu hôm nay',
    'Đang phục vụ': 'Đang phục vụ',
    'Đã xong (Của bạn)': 'Đã xong (Của bạn)',
    'Đã hoàn thành': 'Đã hoàn thành',
    'Active Orders': 'Đơn đang phục vụ',
    'Avg Bill': 'TB đơn hàng',
    'TB Đơn': 'TB Đơn',
    'Pending': 'Chờ xử lý',
    'Cooking': 'Đang chế biến',
    'Ready': 'Sẵn sàng',
    'Completed': 'Hoàn thành',
    'Cancelled': 'Đã hủy',
    'Pay': 'Thanh toán',
    'Takeaway': 'Mang về',
    'No orders found': 'Chưa có đơn hàng nào',
    'Select an Order': 'Chọn một đơn hàng',
    'Personal View': 'Cá nhân',
    'Global View': 'Toàn cục',
    // 'Search ID or Table...': 'Tìm ID hoặc Bàn...', // Removed Duplicate

    // Menu
    'Manage items': 'Quản lý món và kho thủ công',
    'Add Item': 'Thêm món',
    'Search...': 'Tìm kiếm...',
    'All': 'Tất cả',
    'Coffee': 'Cà phê',
    'Non Coffee': 'Không cà phê',
    'Matcha': 'Matcha',
    'Food': 'Đồ ăn',
    'Current Order': 'Đơn hiện tại',
    'Subtotal': 'Tạm tính',
    'Total Amount': 'Tổng cộng',
    'Confirm Order': 'Xác nhận đơn',
    'Cart is empty': 'Giỏ hàng trống',
    'Your Cart': 'Giỏ hàng của bạn',
    'View Cart': 'Xem giỏ hàng',
    'New Menu Item': 'Thêm món mới',
    'Edit Item': 'Sửa món',
    'Select Order Type': 'Chọn hình thức',
    'Dine-in': 'Dùng tại bàn',
    'Select table': 'Chọn bàn',
    'Draft': 'Giỏ tạm',
    'Selected': 'Đã chọn',
    'Batch Add': 'Thêm món',
    'Manage': 'Quản lý',
    'Exit': 'Thoát',

    // FloorPlan
    'Main Hall': 'Sảnh chính',
    'Live': 'Trực tiếp',
    'Editor Mode': 'Chế độ sửa',
    'Edit Layout': 'Sửa sơ đồ',
    'Save Changes': 'Lưu thay đổi',
    'Done': 'Xong',
    'Guests': 'Khách',
    'Occupied': 'Đang dùng',
    'Available': 'Bàn trống',
    'Empty Table': 'Bàn trống',
    'Ready for service': 'Sẵn sàng phục vụ',
    'Check In & Order': 'Mở bàn & Gọi món',
    'Edit Order': 'Sửa đơn',
    'Bill': 'Hóa đơn',
    'Total': 'Tổng',
    'Add Items': 'Thêm món',
    'Split / Merge Table': 'Chuyển / Gộp bàn',
    'Shape': 'Hình dáng',
    'Seats': 'Số ghế',
    'Table Actions': 'Thao tác bàn',
    'Move Table': 'Chuyển bàn',
    'Merge Table': 'Gộp bàn',
    'From Table': 'Từ bàn',
    'Select an empty table to move to': 'Chọn bàn trống để chuyển đến',
    'Select an occupied table to merge with': 'Chọn bàn đang dùng để gộp vào',
    'No empty tables available': 'Không có bàn trống',
    'No other occupied tables': 'Không có bàn nào để gộp',
    'Failed to Save Order': 'Lỗi khi lưu đơn hàng',
    'Table Opened Successfully': 'Đã mở bàn mới thành công',
    'Open Table': 'Mở bàn mới',
    'Select Item to Add': 'Chọn món để thêm',
    'Add Table': 'Thêm bàn',

    // Inventory
    'Inventory Management': 'Quản lý kho hàng',
    'Manage stock': 'Quản lý tồn kho và định lượng',
    'Stock View': 'Tồn kho',
    'Yield Analysis': 'Định lượng',
    'Sync': 'Đồng bộ',
    'Total Value': 'Tổng giá trị',
    'Low Stock': 'Sắp hết',
    'Action Needed': 'Cần nhập',
    'All Good': 'Ổn định',
    'Top Item': 'Top nguyên liệu',
    'Stock In': 'Nhập kho',
    'Add new ingredients': 'Thêm nguyên liệu mới',
    'Ingredient Name': 'Tên nguyên liệu',
    'Quantity': 'Số lượng',
    'Unit': 'Đơn vị',
    'Category': 'Danh mục',
    'Add Stock': 'Thêm hàng',
    'Stock Added': 'Đã thêm',
    'Inventory List': 'Danh sách kho',
    'Track all ingredients': 'Theo dõi nguyên liệu',
    'Potential Yield Analysis': 'Phân tích định lượng',
    'Theoretical max': 'Số lượng món tối đa có thể bán',
    'Item Name': 'Tên hàng',
    'Stock Level': 'Tồn kho',
    'Est. Yield': 'Ước tính',
    'Action': 'Thao tác',
    'units': 'đơn vị',
    'Manual Stock': 'Kho thủ công',
    'No recipe defined': 'Chưa có công thức',
    // Inventory Categories & Statuses
    'Pantry': 'Đồ khô',
    'Dairy': 'Sữa & Chế phẩm',
    'Produce': 'Rau củ',
    'Packaging': 'Bao bì',
    'Meat': 'Thịt',
    'Seafood': 'Hải sản',
    'Beverages': 'Đồ uống',
    'Critical': 'Hết hàng',
    'Low': 'Sắp hết',
    'Good': 'Tốt',
    'packs': 'gói',
    'pcs': 'cái',

    // Payment Modal & Split Bill
    'Confirm Payment': 'Xác nhận thanh toán',
    'Total to Pay': 'Tổng tiền thanh toán',
    'Order #': 'Đơn hàng #',
    'Auto Print Receipt': 'Tự động in hóa đơn',
    'Complete Order': 'Hoàn tất đơn hàng',
    'Scan to pay': 'Quét mã để thanh toán',
    'VietQR Payment': 'Thanh toán VietQR',
    'Account Owner': 'Tên chủ tài khoản',
    'Account Number': 'Số tài khoản',
    'Bank': 'Ngân hàng',
    'Memo': 'Nội dung',
    'Bank settings required': 'Vui lòng cấu hình tài khoản trong Cài đặt',
    'Cannot apply discount to partially paid order': 'Không thể giảm giá cho đơn đã thanh toán một phần',
    'Giảm giá đang tắt trong Cài đặt.': 'Tính năng giảm giá đang tắt trong Cài đặt.',
    'Không có quyền thực hiện giảm giá.': 'Bạn không có quyền thực hiện giảm giá.',
    'Sai PIN.': 'Sai mã PIN.',
    'Giới hạn giảm giá tối đa là': 'Giới hạn giảm giá tối đa là',
    'Giảm giá không thể quá 100%': 'Giảm giá không thể quá 100%',
    'Giảm giá không thể lớn hơn tổng tiền': 'Giảm giá không thể lớn hơn tổng tiền',
    'Apply Discount': 'Áp dụng giảm giá',
    'Discount Percentage': 'Phần trăm giảm giá',
    'Discount Amount': 'Số tiền giảm giá',
    'New Total:': 'Thành tiền mới:',
    'Confirm Discount': 'Xác nhận giảm giá',
    'Cannot split a partially paid order': 'Không thể tách đơn đã thanh toán một phần',
    'Tính năng tách bill đang tắt.': 'Tính năng tách bill đang tắt.',
    'Không có quyền thực hiện tách bill.': 'Bạn không có quyền tách bill.',
    'Split Bill Items': 'Chọn món cần tách',
    'Select items to move to a new bill.': 'Chọn các món để chuyển sang đơn mới.',
    'New Bill Subtotal': 'Tổng tiền đơn mới',
    'Next: Select Table': 'Tiếp tục: Chọn bàn',
    'Select New Table': 'Chọn bàn đích',
    'Bill Split Successful!': 'Tách đơn thành công!',
    'Items moved to new order.': 'Items moved to new order.',
    'Choose where to move the split items:': 'Chọn nơi chuyển các món đã tách đến:',
    'Failed to split order: ': 'Lỗi tách đơn: ',
    'Paid:': 'Đã trả:',
    'Remaining to Pay': 'Còn lại',
    'Edit Discount': 'Sửa giảm giá',
    'Split Bill': 'Tách Bill',
    'Max allowed:': 'Tối đa:',
    'Empty': 'Trống',
    'Cannot split order with single item': 'Không thể tách đơn chỉ có 1 món',
    'Order total must be greater than 0': 'Tổng tiền đơn hàng phải lớn hơn 0',
    'Cannot remove last item. Cancel order instead.': 'Không thể xóa món cuối cùng. Vui lòng hủy đơn hàng.',
    
    // Reset Table Flow
    'Confirm Reset Order': 'Xác nhận hủy đơn?',
    'Last item removal warning': 'Xóa món cuối cùng sẽ hủy toàn bộ đơn hàng và trả bàn. Tiếp tục?',
    'Table Reset Success': 'Đã xóa món cuối. Bàn đã được reset.',

    // --- SETTINGS.TSX TEXT (VI Source -> VI Target: Keep as is) ---
    // Section: Permissions & Roles
    'Bán hàng & Vận hành': 'Bán hàng & Vận hành',
    'Truy cập màn hình POS': 'Truy cập màn hình POS',
    'Quản lý bàn (Gộp/Tách/Chuyển)': 'Quản lý bàn (Gộp/Tách/Chuyển)',
    'Mở ca làm việc': 'Mở ca làm việc',
    'Chốt ca & Đếm tiền': 'Chốt ca & Đếm tiền',
    'Thao tác nhạy cảm': 'Thao tác nhạy cảm',
    'Giảm giá đơn hàng': 'Giảm giá đơn hàng',
    'Huỷ món đã gọi (Sau khi bếp làm)': 'Huỷ món đã gọi (Sau khi bếp làm)',
    'Hoàn tiền / Mở két tiền': 'Hoàn tiền / Mở két tiền',
    'Xoá hoàn toàn đơn hàng': 'Xoá hoàn toàn đơn hàng',
    'Quản lý & Cấu hình': 'Quản lý & Cấu hình',
    'Xem báo cáo doanh thu': 'Xem báo cáo doanh thu',
    'Chỉnh sửa thực đơn & Giá': 'Chỉnh sửa thực đơn & Giá',
    'Quản lý nhân viên': 'Quản lý nhân viên',
    'Cấu hình hệ thống': 'Cấu hình hệ thống',
    'Owner': 'Chủ quán',
    'Chủ quán - Toàn quyền truy cập mọi chức năng hệ thống.': 'Chủ quán - Toàn quyền truy cập mọi chức năng hệ thống.',
    'Shift Manager': 'Quản lý ca',
    'Quản lý ca - Vận hành, báo cáo và xử lý sự cố.': 'Quản lý ca - Vận hành, báo cáo và xử lý sự cố.',
    'Cashier': 'Thu ngân',
    'Thu ngân - Chuyên trách thanh toán và két tiền.': 'Thu ngân - Chuyên trách thanh toán và két tiền.',
    'Server': 'Phục vụ',
    'Phục vụ - Chỉ order và quản lý bàn cơ bản.': 'Phục vụ - Chỉ order và quản lý bàn cơ bản.',
    'Kitchen/Bar': 'Bếp/Bar',
    'Bếp/Bar - Không truy cập POS, chỉ xem màn hình hiển thị (KDS).': 'Bếp/Bar - Không truy cập POS, chỉ xem màn hình hiển thị (KDS).',
    'Accountant': 'Kế toán',
    'Kế toán - Chỉ xem báo cáo để đối soát.': 'Kế toán - Chỉ xem báo cáo để đối soát.',

    // Section: Status & UI Elements
    'Vận hành: Mượt': 'Vận hành: Mượt',
    'Cần chú ý': 'Cần chú ý',
    'Lỗi': 'Lỗi',
    'Nhập': 'Nhập',
    'để xác nhận:': 'để xác nhận:',
    'Huỷ': 'Huỷ',
    'Hoá đơn in mẫu': 'Hoá đơn in mẫu',
    'Chế độ xem trước (Sandbox)': 'Chế độ xem trước (Sandbox)',
    'Đóng': 'Đóng',
    'Đã sao chép HTML': 'Đã sao chép HTML',
    'Copy nội dung': 'Copy nội dung',
    'Bật tính năng': 'Bật tính năng',
    'Đồng ý bật': 'Đồng ý bật',
    'Không tìm thấy cài đặt nào phù hợp': 'Không tìm thấy cài đặt nào phù hợp',
    'Saving...': 'Đang lưu...',
    'Saved': 'Đã lưu',
    'Tìm cài đặt...': 'Tìm cài đặt...',
    'Đổi mật khẩu': 'Đổi mật khẩu',
    'Mật khẩu mới': 'Mật khẩu mới',
    'Xác nhận mật khẩu mới': 'Xác nhận mật khẩu mới',
    'Cập nhật': 'Cập nhật',
    'Mật khẩu không khớp': 'Mật khẩu không khớp',
    'Đổi mật khẩu thành công': 'Đổi mật khẩu thành công',
    'Xoá dữ liệu trên máy này?': 'Xoá dữ liệu trên máy này?',
    'Thao tác này không thể hoàn tác. Nhập DELETE để xác nhận.': 'Thao tác này không thể hoàn tác. Nhập DELETE để xác nhận.',
    'Xoá': 'Xoá',
    'Đăng xuất?': 'Đăng xuất?',
    'Bạn sẽ đăng xuất khỏi phiên làm việc hiện tại.': 'Bạn sẽ đăng xuất khỏi phiên làm việc hiện tại.',
    'Đăng xuất': 'Đăng xuất',
    'Administrator access required': 'Cần quyền Quản trị viên',
    'Administrator access required to manage users': 'Cần quyền Quản trị viên để quản lý user',
    'Quản lý User & Mã PIN': 'Quản lý User & Mã PIN',
    'Set PIN for': 'Đặt mã PIN cho',
    'Save PIN': 'Lưu mã PIN',
    'PIN updated successfully': 'Cập nhật PIN thành công',

    // Section: Config Keys & Descriptions
    'Cài đặt hệ thống': 'Cài đặt hệ thống',
    'Quản lý toàn bộ cấu hình quán': 'Quản lý toàn bộ cấu hình quán',
    'Quán & Bán hàng': 'Quán & Bán hàng',
    'Thiết lập luồng order, thanh toán và quản lý bàn': 'Thiết lập luồng order, thanh toán và quản lý bàn',
    'Luồng bán hàng': 'Luồng bán hàng',
    'Tạo đơn nhanh': 'Tạo đơn nhanh',
    'Bỏ qua bước chọn bàn, vào thẳng menu (giảm bước)': 'Bỏ qua bước chọn bàn, vào thẳng menu (giảm bước)',
    'Kiểu order mặc định': 'Kiểu order mặc định',
    'Chọn hình thức phục vụ chính của quán': 'Chọn hình thức phục vụ chính của quán',
    'Tại bàn': 'Tại bàn',
    'Mang đi': 'Mang đi',
    'Giao hàng': 'Giao hàng',
    'Hỏi xác nhận khi huỷ món': 'Hỏi xác nhận khi huỷ món',
    'Tránh nhân viên bấm nhầm xoá món đã gọi': 'Tránh nhân viên bấm nhầm xoá món đã gọi',
    'Thanh toán': 'Thanh toán',
    'Cho phép tách bill': 'Cho phép tách bill',
    'Tách đơn lớn thành nhiều đơn nhỏ để thanh toán': 'Tách đơn lớn thành nhiều đơn nhỏ để thanh toán',
    'Cho phép gộp bill': 'Cho phép gộp bill',
    'Gộp nhiều bàn/đơn vào một hóa đơn thanh toán': 'Gộp nhiều bàn/đơn vào một hóa đơn thanh toán',
    'Bật tính năng giảm giá': 'Bật tính năng giảm giá',
    'Cho phép nhập giảm giá theo % hoặc số tiền': 'Cho phép nhập giảm giá theo % hoặc số tiền',
    'Giới hạn giảm giá tối đa': 'Giới hạn giảm giá tối đa',
    'Mức % giảm giá cao nhất nhân viên được phép nhập': 'Mức % giảm giá cao nhất nhân viên được phép nhập',
    'Bàn & Khu vực': 'Bàn & Khu vực',
    'Bật quản lý bàn': 'Bật quản lý bàn',
    'Hiển thị sơ đồ bàn (Tắt nếu chỉ bán mang đi)': 'Hiển thị sơ đồ bàn (Tắt nếu chỉ bán mang đi)',
    'Bật quản lý khu vực': 'Bật quản lý khu vực',
    'Phân chia bàn theo tầng hoặc phòng': 'Phân chia bàn theo tầng hoặc phòng',
    'Cảnh báo bàn mở quá lâu': 'Cảnh báo bàn mở quá lâu',
    'Hiện cảnh báo khi khách ngồi quá thời gian quy định': 'Hiện cảnh báo khi khách ngồi quá thời gian quy định',
    'Thời gian giới hạn': 'Thời gian giới hạn',
    'Số phút tối đa trước khi cảnh báo': 'Số phút tối đa trước khi cảnh báo',
    'In & Hóa đơn': 'In & Hóa đơn',
    'Máy in, nội dung hóa đơn và thao tác in nhanh': 'Máy in, nội dung hóa đơn và thao tác in nhanh',
    'Máy in': 'Máy in',
    'Tên máy in': 'Tên máy in',
    'Kiểm tra kết nối': 'Kiểm tra kết nối',
    'Gửi tín hiệu đến máy in': 'Gửi tín hiệu đến máy in',
    'Khổ giấy': 'Khổ giấy',
    'Hành vi in': 'Hành vi in',
    'Tự động in sau thanh toán': 'Tự động in sau thanh toán',
    'Bấm Thanh toán là in ngay': 'Bấm Thanh toán là in ngay',
    'In phiếu tạm khi tạo đơn': 'In phiếu tạm khi tạo đơn',
    'Dùng khi muốn giữ bill tạm': 'Dùng khi muốn giữ bill tạm',
    'In lại khi chỉnh sửa đơn': 'In lại khi chỉnh sửa đơn',
    'Thêm món/sửa món sẽ in lại': 'Thêm món/sửa món sẽ in lại',
    'Nội dung hóa đơn': 'Nội dung hóa đơn',
    'Hiện QR thanh toán': 'Hiện QR thanh toán',
    'Khách quét mã chuyển khoản nhanh': 'Khách quét mã chuyển khoản nhanh',
    'Hiện thông tin quán': 'Hiện thông tin quán',
    'Tên/địa chỉ/SĐT trên hóa đơn': 'Tên/địa chỉ/SĐT trên hóa đơn',
    'Tên Wifi': 'Tên Wifi',
    'Mật khẩu Wifi': 'Mật khẩu Wifi',
    'In ở cuối hóa đơn cho khách tại bàn': 'In ở cuối hóa đơn cho khách tại bàn',
    'Cỡ chữ hóa đơn': 'Cỡ chữ hóa đơn',
    'Khuyên dùng ‘Vừa’ cho 80mm': 'Khuyên dùng ‘Vừa’ cho 80mm',
    'Nhỏ': 'Nhỏ',
    'Vừa': 'Vừa',
    'Lớn': 'Lớn',
    'In ghi chú món': 'In ghi chú món',
    'Ghi chú nằm dưới tên món': 'Ghi chú nằm dưới tên món',
    'Test in': 'Test in',
    'In hóa đơn test': 'In hóa đơn test',
    'Kiểm tra máy in trước khi bán': 'Kiểm tra máy in trước khi bán',
    'Nhân viên & Quyền hạn': 'Nhân viên & Quyền hạn',
    'Phân quyền, giới hạn thao tác nhạy cảm và bảo mật': 'Phân quyền, giới hạn thao tác nhạy cảm và bảo mật',
    'Vai trò nhanh (Preset Roles)': 'Vai trò nhanh (Preset Roles)',
    'Tuỳ chỉnh quyền chi tiết': 'Tuỳ chỉnh quyền chi tiết',
    'Quyền quan trọng (Staff Permissions)': 'Quyền quan trọng (Staff Permissions)',
    'Cho phép huỷ món': 'Cho phép huỷ món',
    'Rủi ro: Nhân viên có thể huỷ đơn gian lận sau khi thu tiền.': 'Rủi ro: Nhân viên có thể huỷ đơn gian lận sau khi thu tiền.',
    'Cho phép nhân viên tự ý huỷ món có thể dẫn đến thất thoát doanh thu. Bạn có chắc chắn muốn bật?': 'Cho phép nhân viên tự ý huỷ món có thể dẫn đến thất thoát doanh thu. Bạn có chắc chắn muốn bật?',
    'Cho phép xóa hoàn toàn đơn hàng': 'Cho phép xóa hoàn toàn đơn hàng',
    'Rủi ro: Mất dữ liệu đơn hàng.': 'Rủi ro: Mất dữ liệu đơn hàng.',
    'Cho phép nhân viên xóa hoàn toàn đơn hàng (Cancel Order). Bạn có chắc chắn?': 'Cho phép nhân viên xóa hoàn toàn đơn hàng (Cancel Order). Bạn có chắc chắn?',
    'Cho phép giảm giá': 'Cho phép giảm giá',
    'Rủi ro: Áp dụng giảm giá sai quy định.': 'Rủi ro: Áp dụng giảm giá sai quy định.',
    'Việc cho phép nhân viên tự giảm giá có thể bị lạm dụng. Bạn có chắc chắn?': 'Việc cho phép nhân viên tự giảm giá có thể bị lạm dụng. Bạn có chắc chắn?',
    'Cho phép xem báo cáo': 'Cho phép xem báo cáo',
    'Nhân viên sẽ thấy được doanh thu tổng của quán.': 'Nhân viên sẽ thấy được doanh thu tổng của quán.',
    'Cho phép hoàn tiền / Mở két': 'Cho phép hoàn tiền / Mở két',
    'Rủi ro cao: Thất thoát tiền mặt trực tiếp.': 'Rủi ro cao: Thất thoát tiền mặt trực tiếp.',
    'CẢNH BÁO: Quyền này cho phép nhân viên mở két tiền và hoàn trả tiền mặt. Bạn có chắc chắn?': 'CẢNH BÁO: Quyền này cho phép nhân viên mở két tiền và hoàn trả tiền mặt. Bạn có chắc chắn?',
    'Mã PIN thao tác nhạy cảm': 'Mã PIN thao tác nhạy cảm',
    'Yêu cầu PIN khi huỷ món': 'Yêu cầu PIN khi huỷ món',
    'Bắt buộc nhập mã PIN chủ quán hoặc quản lý': 'Bắt buộc nhập mã PIN chủ quán hoặc quản lý',
    'Yêu cầu PIN khi giảm giá': 'Yêu cầu PIN khi giảm giá',
    'Ngăn chặn giảm giá tuỳ tiện': 'Ngăn chặn giảm giá tuỳ tiện',
    'Dùng để duyệt các thao tác nhạy cảm': 'Dùng để duyệt các thao tác nhạy cảm',
    'Cấu hình Manager (Manager Config)': 'Cấu hình Manager (Manager Config)',
    'Giao diện & Trải nghiệm': 'Giao diện & Trải nghiệm',
    'Tùy chỉnh tốc độ thao tác, hiển thị và phím tắt': 'Tùy chỉnh tốc độ thao tác, hiển thị và phím tắt',
    'Giao diện & Ngôn ngữ': 'Giao diện & Ngôn ngữ',
    'Ngôn ngữ': 'Ngôn ngữ',
    'Áp dụng cho toàn bộ hệ thống, không cần khởi động lại': 'Áp dụng cho toàn bộ hệ thống, không cần khởi động lại',
    'Chế độ hiển thị': 'Chế độ hiển thị',
    'Giao diện Sáng / Tối': 'Giao diện Sáng / Tối',
    'Hệ thống (System)': 'Hệ thống (System)',
    'Tối (Dark)': 'Tối (Dark)',
    'Sáng (Light)': 'Sáng (Light)',
    'Tự động theo khung giờ (06:00–18:00 sáng, 18:00–06:00 tối)': 'Tự động theo khung giờ (06:00–18:00 sáng, 18:00–06:00 tối)',
    'Tự động chuyển đổi Light/Dark': 'Tự động chuyển đổi Light/Dark',
    'Chỉ áp dụng khi chọn System': 'Chỉ áp dụng khi chọn System',
    'Giờ bắt đầu Sáng': 'Giờ bắt đầu Sáng',
    'Giờ bắt đầu Tối': 'Giờ bắt đầu Tối',
    'Tốc độ thao tác': 'Tốc độ thao tác',
    'Chạm 1 lần để thêm món': 'Chạm 1 lần để thêm món',
    'Mặc định trên tablet giúp order nhanh hơn': 'Mặc định trên tablet giúp order nhanh hơn',
    'Hiện bàn phím số': 'Hiện bàn phím số',
    'Hiện popup nhập số lượng khi chọn món': 'Hiện popup nhập số lượng khi chọn món',
    'Âm thanh beep khi thêm món': 'Âm thanh beep khi thêm món',
    'Phản hồi âm thanh giúp biết đã nhận lệnh': 'Phản hồi âm thanh giúp biết đã nhận lệnh',
    'Hiển thị': 'Hiển thị',
    'Mật độ giao diện': 'Mật độ giao diện',
    'Chọn độ thoáng của các nút bấm': 'Chọn độ thoáng của các nút bấm',
    'Thoáng': 'Thoáng',
    'Dày (Compact)': 'Dày (Compact)',
    'Cỡ chữ tổng': 'Cỡ chữ tổng',
    'Ảnh hưởng toàn bộ ứng dụng': 'Ảnh hưởng toàn bộ ứng dụng',
    'Chế độ tương phản cao': 'Chế độ tương phản cao',
    'Dễ nhìn hơn trong môi trường ánh sáng mạnh': 'Dễ nhìn hơn trong môi trường ánh sáng mạnh',
    'Shortcut': 'Shortcut',
    'Bật phím tắt bàn phím': 'Bật phím tắt bàn phím',
    'F2: Thanh toán, F3: Tìm món...': 'F2: Thanh toán, F3: Tìm món...',
    'Xem danh sách phím tắt': 'Xem danh sách phím tắt',
    'Hiển thị bảng tra cứu phím tắt': 'Hiển thị bảng tra cứu phím tắt',
    'Báo cáo & Kiểm soát': 'Báo cáo & Kiểm soát',
    'Giữ số liệu sạch, hạn chế thất thoát, kiểm soát vận hành': 'Giữ số liệu sạch, hạn chế thất thoát, kiểm soát vận hành',
    'Nhật ký thao tác (Audit)': 'Nhật ký thao tác (Audit)',
    'Ghi log thao tác nhạy cảm': 'Ghi log thao tác nhạy cảm',
    'Lưu lại khi nhân viên huỷ món, giảm giá hoặc hoàn tiền': 'Lưu lại khi nhân viên huỷ món, giảm giá hoặc hoàn tiền',
    'Ghi log đổi ca': 'Ghi log đổi ca',
    'Lưu thời điểm và người thực hiện giao ca': 'Lưu thời điểm và người thực hiện giao ca',
    'Thời gian lưu log': 'Thời gian lưu log',
    'Tự động xoá log cũ để giảm dung lượng': 'Tự động xoá log cũ để giảm dung lượng',
    '7 ngày': '7 ngày',
    '30 ngày': '30 ngày',
    '90 ngày': '90 ngày',
    'Cảnh báo thất thoát': 'Cảnh báo thất thoát',
    'Cảnh báo khi giảm giá cao': 'Cảnh báo khi giảm giá cao',
    'Hiện cảnh báo đỏ nếu % giảm giá vượt mức quy định': 'Hiện cảnh báo đỏ nếu % giảm giá vượt mức quy định',
    'Ngưỡng cảnh báo giảm giá': 'Ngưỡng cảnh báo giảm giá',
    'Ví dụ: 20% - Cao hơn mức này sẽ báo động': 'Ví dụ: 20% - Cao hơn mức này sẽ báo động',
    'Cảnh báo huỷ món bất thường': 'Cảnh báo huỷ món bất thường',
    'Phát hiện nếu một bàn bị huỷ món liên tục': 'Phát hiện nếu một bàn bị huỷ món liên tục',
    'Đóng ca (Shift Close)': 'Đóng ca (Shift Close)',
    'Bắt buộc đóng ca cuối ngày': 'Bắt buộc đóng ca cuối ngày',
    'Không thể bán hàng ngày mới nếu chưa chốt ca cũ': 'Không thể bán hàng ngày mới nếu chưa chốt ca cũ',
    'Yêu cầu nhập tiền thực thu': 'Yêu cầu nhập tiền thực thu',
    'Nhân viên phải đếm tiền và nhập số liệu khi đóng ca': 'Nhân viên phải đếm tiền và nhập số liệu khi đóng ca',
    'Xuất báo cáo đóng ca mẫu': 'Xuất báo cáo đóng ca mẫu',
    'Xem trước mẫu báo cáo Z-Report': 'Xem trước mẫu báo cáo Z-Report',
    'Quyền xem báo cáo & Dữ liệu': 'Quyền xem báo cáo & Dữ liệu',
    'Ai được xem báo cáo': 'Ai được xem báo cáo',
    'Giới hạn đúng người, đúng việc': 'Giới hạn đúng người, đúng việc',
    'Chỉ chủ quán': 'Chỉ chủ quán',
    'Chủ + quản lý': 'Chủ + quản lý',
    'Tất cả nhân viên': 'Tất cả nhân viên',
    'Ẩn doanh thu chi tiết': 'Ẩn doanh thu chi tiết',
    'Nhân viên chỉ thấy số lượng, không thấy tiền': 'Nhân viên chỉ thấy số lượng, không thấy tiền',
    'Cho phép xuất dữ liệu': 'Cho phép xuất dữ liệu',
    'Chỉ nên bật cho chủ quán': 'Chỉ nên bật cho chủ quán',
    'Hệ thống & An toàn': 'Hệ thống & An toàn',
    'Bán ổn định khi mất mạng, bảo vệ dữ liệu, yên tâm vận hành': 'Bán ổn định khi mất mạng, bảo vệ dữ liệu, yên tâm vận hành',
    'Offline & Đồng bộ': 'Offline & Đồng bộ',
    'Tự động đồng bộ': 'Tự động đồng bộ',
    'Tự đẩy dữ liệu lên server khi có mạng': 'Tự đẩy dữ liệu lên server khi có mạng',
    'Đồng bộ ngay': 'Đồng bộ ngay',
    'Đẩy thủ công các đơn Offline lên hệ thống': 'Đẩy thủ công các đơn Offline lên hệ thống',
    'Trạng thái mạng': 'Trạng thái mạng',
    'Đơn chờ đồng bộ': 'Đơn chờ đồng bộ',
    'Lần đồng bộ cuối': 'Lần đồng bộ cuối',
    'Lỗi đồng bộ': 'Lỗi đồng bộ',
    'Sao lưu': 'Sao lưu',
    'Xuất dữ liệu': 'Xuất dữ liệu',
    'Tải về file dự phòng (JSON)': 'Tải về file dự phòng (JSON)',
    'Nhập dữ liệu': 'Nhập dữ liệu',
    'Khôi phục từ file backup': 'Khôi phục từ file backup',
    'Danger Zone': 'Danger Zone',
    'Xoá dữ liệu cục bộ': 'Xoá dữ liệu cục bộ',
    'Thao tác này sẽ xoá toàn bộ dữ liệu trên thiết bị này.': 'Thao tác này sẽ xoá toàn bộ dữ liệu trên thiết bị này.',
    'Chạy kiểm tra vận hành': 'Chạy kiểm tra vận hành',
    'Quét lỗi cấu hình và rủi ro bảo mật': 'Quét lỗi cấu hình và rủi ro bảo mật',
    'Kết quả kiểm tra': 'Kết quả kiểm tra',
    'Đạt': 'Đạt',
    'Cảnh báo': 'Cảnh báo',
    'Thất bại': 'Thất bại',
    'Bank (VietQR)': 'Bank (VietQR)',
    'Ngân hàng': 'Ngân hàng',
    'Số tài khoản': 'Số tài khoản',
    'Tên chủ tài khoản': 'Tên chủ tài khoản',
    'Chọn ngân hàng': 'Chọn ngân hàng',
    'Lưu cấu hình ngân hàng': 'Lưu cấu hình ngân hàng',
    'LoginDescription': 'Một POS toàn diện dành cho nhà hàng, quán cà phê, quán bar bao gồm bảng điều khiển, quản lý thực đơn, sơ đồ bàn, theo dõi đơn hàng và kho. Ứng dụng miễn phí xây dựng bởi Đức Ngô',
    'Register text': 'Đăng ký để bắt đầu quản lý nhà hàng.',
    'Login text': 'Vui lòng nhập thông tin để đăng nhập.',
    'Full Name': 'Họ tên',
    'Email Address': 'Email',
    'Password': 'Mật khẩu',
    'Confirm Password': 'Xác nhận mật khẩu',
    'Remember me': 'Ghi nhớ đăng nhập',
    'Forgot password?': 'Quên mật khẩu?',
    'Create Account': 'Tạo tài khoản',
    'Already have an account?': 'Đã có tài khoản?',
    'Don\'t have an account?': 'Chưa có tài khoản?',
    'Sign In': 'Đăng nhập',
    'Create an Account': 'Tạo tài khoản',
  }
};

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export const ThemeProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [themeMode, setThemeMode] = useState<'light' | 'dark' | 'system'>('system');
  const [effectiveTheme, setEffectiveTheme] = useState<Theme>('dark');
  const [language, setLanguage] = useState<Language>('vi');
  const [brightness, setBrightness] = useState(100);
  const [themeConfig, setThemeConfig] = useState<ThemeConfig>({
    mode: 'system',
    scheduleEnabled: false,
    dayStart: '06:00',
    nightStart: '18:00'
  });

  useEffect(() => {
    // Load from local storage if available
    const savedLang = localStorage.getItem('app_language') as Language;
    if (savedLang) setLanguage(savedLang);
  }, []);

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const calculateTheme = useCallback(() => {
    if (themeConfig.mode === 'system') {
        if (themeConfig.scheduleEnabled) {
            const now = new Date();
            const timeStr = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
            if (timeStr >= themeConfig.dayStart && timeStr < themeConfig.nightStart) {
                return 'light';
            } else {
                return 'dark';
            }
        } else {
            return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
        }
    }
    return themeConfig.mode;
  }, [themeConfig]);

  useEffect(() => {
    const t = calculateTheme();
    setEffectiveTheme(t);
    const root = window.document.documentElement;
    root.classList.remove('light', 'dark');
    root.classList.add(t);
  }, [calculateTheme]);

  const setTheme = (t: Theme) => {
      // Manual override sets mode to specific
      setThemeConfig(prev => ({ ...prev, mode: t }));
  };

  const t = useCallback((key: string) => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <ThemeContext.Provider value={{
      theme: effectiveTheme,
      setTheme,
      language,
      setLanguage,
      brightness,
      setBrightness,
      t,
      setThemeConfig
    }}>
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = () => {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error('useTheme must be used within a ThemeProvider');
  }
  return context;
};
